---
# tasks file for install.fail2ban

- name: Install fail2ban package
  apt:
    pkg: fail2ban
    state: present

- name: Ensure fail2ban is up and running
  service:
    name: fail2ban
    state: started
    enabled: yes
