---
# tasks file for install.docker

- name: install pre-requisites
  apt: 
    name: "{{ item }}"
    state: present
  with_items:
  - apt-transport-https
  - ca-certificates
  

- name: Add Docker apt key.
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
    update_cache: yes
   
- name: Install docker package
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - docker-ce
  - docker-compose
  - python-docker
