---
# tasks file for docker.nginx

# first few tasks are going to be making some directories to put things in.

- name: Create basic config directories
  file:
    path: /etc/nginx-proxy/{{ item }}
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
  - conf.d
  - certs

- name: generate dhparam file
  command: /usr/bin/openssl dhparam -out /etc/nginx-proxy/ssl/dhparam.pem 2048
  args:
    creates: /etc/nginx-proxy/ssl/dhparam.pem
  notify:
  - restart_nginx

- name: Put a base config file into place.
  copy:
    src: files/nginx.conf
    dest: /etc/nginx-proxy/nginx.conf
    owner: root
    group: root
    mode: 0644

- name: Template in based on the docker dictionary
  template:
    src: templates/proxy-site.conf.j2
    dest: /etc/nginx-proxy/conf.d/{{ item.key }}.conf
    owner: root
    group: root
    mode: 0644
  with_dict: "{{ docker_sites }}"

- name: Copy in the worldcon.ie file which is nothing but redirects
  copy:
    src: files/worldcon.ie.conf
    dest: /etc/nginx-proxy/conf.d/worldcon.ie.conf
    owner: root
    group: root
    mode: 0644

# What are we doing with the SSL certificates here.
# 

- name: lets try putting this all in a container and pulling it together
  docker_container:
    image: "nginx:1.14.0"
    name: nginx-proxy
    volumes:
    - "/etc/nginx-proxy:/etc/nginx:ro"
    - "{{ nginx_base_directory }}/defaults:/usr/share/nginx/html:ro"
    - "/etc/lets-encrypt/:etc/nginx/ssl:ro" 
    ports:
    - '80:80'
    - '443:443'
    exposed_ports:
    - '80'
    - '443'
    state: started
    restart_policy: always
    log_driver: syslog
    log_options:
      tag: nginx-proxy
